name: 🔧 Build Issue
description: Report problems building publications locally
title: "[Build] "
labels: [ "build_sys", "question" ]
body:
  - type: markdown
    attributes:
      value: |
        Havin g trouble building publications? Please provide details so we can help.

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of build issue are you experiencing?
      options:
        - Build fails with error
        - Build succeeds but output is incorrect
        - Configuration issue
        - Missing dependency
        - Other
    validations:
      required: true

  - type: input
    id: publication
    attributes:
      label: Publication (if specific)
      description: Which publication are you trying to build? (Leave blank if building all)
      placeholder: e.g., "article-01" or "make all"
    validations:
      required: false

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: What command did you run?
      placeholder: |
        e.g., 
        make article-01
        make all
        make OUTPUT_DIR=public article-01
      render: shell
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: What error message did you receive?
      placeholder: Paste the complete error output here
      render: shell
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your system
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 13, Windows 11]
        - Make version: [e.g., GNU Make 4.3]
        - Pandoc version: [e.g., pandoc 3.1.2]
        - LaTeX distribution: [e.g., TeX Live 2023]
      value: |
        - OS: 
        - Make version: 
        - Pandoc version: 
        - LaTeX distribution: 
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to resolve this?
      placeholder: |
        - Checked documentation
        - Verified dependencies
        - Tried clean build
        - etc.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (Optional)
      description: Any other information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      description: Please confirm you have done the following
      options:
        - label: I have verified that required dependencies are installed
          required: true
        - label: I have searched existing issues for similar problems
          required: true
